# Generated by Django 5.0.1 on 2024-01-15 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NccOutLet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('totalcertifiedoutlet', models.IntegerField()),
                ('outletvisited', models.IntegerField()),
                ('outletwithdevice', models.IntegerField()),
                ('totaldeviceinoutlet', models.IntegerField()),
                ('totaldevicesold', models.IntegerField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReactivationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('totalcall', models.IntegerField()),
                ('successfulcall', models.IntegerField()),
                ('unsuccessfulcall', models.IntegerField()),
                ('successfulbundle', models.IntegerField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Broadband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('MSISDN', models.IntegerField()),
                ('IMEI', models.IntegerField()),
                ('Alternate', models.IntegerField()),
                ('device_type', models.CharField(choices=[('MIFI', 'MIFI'), ('Router', 'Router'), ('ODU', 'ODU'), ('5G Router', '5G Router')], max_length=100)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('region', models.CharField(choices=[('North East', 'North East'), ('North West', 'North West'), ('South East', 'South East'), ('South South', 'South South')], default='North East', max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
