# Generated by Django 5.0.1 on 2024-01-16 03:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadband',
            name='IMEI',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999999), django.core.validators.MinValueValidator(100000000000000)]),
        ),
    ]
