# Generated by Django 5.0.1 on 2024-01-20 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_broadband_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadband',
            name='Alternate',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999, message='Alternate number can not be greater than 11 digits'), django.core.validators.MinValueValidator(10, message='Alternate number can not be less than 11 digits')]),
        ),
        migrations.AlterField(
            model_name='broadband',
            name='MSISDN',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999, message='MSISDN can not be greater than 11 digits'), django.core.validators.MinValueValidator(10000000000, message='MSISDN can not be less than 11 digits')]),
        ),
    ]
