# Generated by Django 5.0.1 on 2024-01-20 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_broadband_alternate_alter_broadband_msisdn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadband',
            name='Alternate',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999, message='IMEI can not be greater than 15 digits'), django.core.validators.MinValueValidator(10000000000, message='IMEI can not be less than 15 digits')]),
        ),
        migrations.AlterField(
            model_name='broadband',
            name='MSISDN',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999, message='IMEI can not be greater than 15 digits'), django.core.validators.MinValueValidator(10000000000, message='IMEI can not be less than 15 digits')]),
        ),
    ]
