# Generated by Django 4.2.2 on 2024-01-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
