# Generated by Django 4.2.2 on 2024-01-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadband',
            name='daily_sales_count',
            field=models.IntegerField(default=0),
        ),
    ]
