# Generated by Django 4.2.2 on 2024-01-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_deviceregistrationanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceregistrationanalytics',
            name='device_type',
            field=models.CharField(choices=[('MIFI', 'MIFI'), ('Router', 'Router'), ('ODU', 'ODU'), ('5G Router', '5G Router')], max_length=100),
        ),
        migrations.AlterField(
            model_name='deviceregistrationanalytics',
            name='region',
            field=models.CharField(choices=[('North East', 'North East'), ('North West', 'North West'), ('South East', 'South East'), ('South South', 'South South')], max_length=100),
        ),
    ]
