# Generated by Django 5.0.1 on 2024-02-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_deviceregistrationanalytics_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadband',
            name='MIFI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadband',
            name='ODU',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadband',
            name='Router',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadband',
            name='_5G_Router',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadband',
            name='achieved_previous_month',
            field=models.FloatField(default=0.0),
        ),
    ]
