# Generated by Django 5.0.1 on 2024-02-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_name_broadband_hse_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadband',
            old_name='device_type',
            new_name='Device_type',
        ),
        migrations.RenameField(
            model_name='broadband',
            old_name='post_date',
            new_name='Post_date',
        ),
        migrations.RenameField(
            model_name='broadband',
            old_name='region',
            new_name='Region',
        ),
        migrations.RenameField(
            model_name='broadband',
            old_name='state',
            new_name='State',
        ),
    ]
