# Generated by Django 5.0.1 on 2024-02-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_device_type_broadband_device_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nccoutlet',
            old_name='name',
            new_name='HSE_name',
        ),
        migrations.RenameField(
            model_name='nccoutlet',
            old_name='outletvisited',
            new_name='Outlet_visited',
        ),
        migrations.RenameField(
            model_name='nccoutlet',
            old_name='outletwithdevice',
            new_name='Outlet_with_device',
        ),
        migrations.RenameField(
            model_name='nccoutlet',
            old_name='post_date',
            new_name='Post_date',
        ),
        migrations.RenameField(
            model_name='nccoutlet',
            old_name='totalcertifiedoutlet',
            new_name='Total_certified_outlet',
        ),
        migrations.RenameField(
            model_name='nccoutlet',
            old_name='totaldeviceinoutlet',
            new_name='Total_devices_in_outlet',
        ),
        migrations.RenameField(
            model_name='nccoutlet',
            old_name='totaldevicesold',
            new_name='Total_devices_sold',
        ),
        migrations.RenameField(
            model_name='reactivationreport',
            old_name='name',
            new_name='HSE_name',
        ),
        migrations.RenameField(
            model_name='reactivationreport',
            old_name='post_date',
            new_name='Post_date',
        ),
        migrations.RenameField(
            model_name='reactivationreport',
            old_name='successfulbundle',
            new_name='Successful_bundle',
        ),
        migrations.RenameField(
            model_name='reactivationreport',
            old_name='successfulcall',
            new_name='Successful_calls',
        ),
        migrations.RenameField(
            model_name='reactivationreport',
            old_name='totalcall',
            new_name='Total_calls',
        ),
        migrations.RenameField(
            model_name='reactivationreport',
            old_name='unsuccessfulcall',
            new_name='Unsuccessful_calls',
        ),
        migrations.AlterField(
            model_name='broadband',
            name='Region',
            field=models.CharField(choices=[('North East', 'North East'), ('North West', 'North West'), ('South East', 'South East'), ('South South', 'South South'), ('Lagos', 'Lagos'), ('West', 'West')], default='North East', max_length=100),
        ),
        migrations.AlterField(
            model_name='deviceregistrationanalytics',
            name='region',
            field=models.CharField(choices=[('North East', 'North East'), ('North West', 'North West'), ('South East', 'South East'), ('South South', 'South South'), ('Lagos', 'Lagos'), ('West', 'West')], max_length=100),
        ),
    ]
