# Generated by Django 5.0.1 on 2024-02-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_archiveddata_maindata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadband',
            old_name='d5G_Router',
            new_name='f5G_Router',
        ),
    ]
