# Generated by Django 5.0.1 on 2024-02-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_d5g_router_broadband_f5g_router'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadband',
            old_name='f5G_Router',
            new_name='d5G_Router',
        ),
    ]
