# Generated by Django 3.2.1 on 2024-03-19 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_uploadphoto_photo_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadband',
            name='Alternate',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'Alternate number must be an 11-digit number.')]),
        ),
        migrations.AlterField(
            model_name='broadband',
            name='IMEI',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{15}$', 'IMEI must be a 15-digit number.')]),
        ),
        migrations.AlterField(
            model_name='broadband',
            name='MSISDN',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'MSISDN must be an 11-digit number.')]),
        ),
    ]
