# Generated by Django 3.2.1 on 2024-03-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20240319_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadphoto',
            name='Region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadphoto',
            name='State',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='broadband',
            name='Device_type',
            field=models.CharField(choices=[('MIFI', 'MIFI'), ('Router', 'Router'), ('ODU', 'ODU'), ('5G Router', '5G Router')], default='MIFI', max_length=100),
        ),
    ]
