# Generated by Django 3.2.1 on 2024-03-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20240320_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactivationreport',
            name='Region',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reactivationreport',
            name='State',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
