# Generated by Django 3.2.1 on 2024-03-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20240320_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactivationreport',
            name='Region',
        ),
        migrations.RemoveField(
            model_name='reactivationreport',
            name='State',
        ),
    ]
