# Generated by Django 3.2.1 on 2024-03-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20240320_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='nccoutlet',
            name='Region',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='nccoutlet',
            name='State',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='reactivationreport',
            name='Region',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='reactivationreport',
            name='State',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='uploadphoto',
            name='Region',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='uploadphoto',
            name='State',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
