# Generated by Django 3.2.1 on 2024-03-21 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20240320_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nccoutlet',
            name='Region',
        ),
        migrations.RemoveField(
            model_name='nccoutlet',
            name='State',
        ),
        migrations.RemoveField(
            model_name='reactivationreport',
            name='Region',
        ),
        migrations.RemoveField(
            model_name='reactivationreport',
            name='State',
        ),
        migrations.RemoveField(
            model_name='uploadphoto',
            name='Region',
        ),
        migrations.RemoveField(
            model_name='uploadphoto',
            name='State',
        ),
        migrations.AddField(
            model_name='nccoutlet',
            name='broadband',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.broadband'),
        ),
        migrations.AddField(
            model_name='reactivationreport',
            name='broadband',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.broadband'),
        ),
        migrations.AddField(
            model_name='uploadphoto',
            name='broadband',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.broadband'),
        ),
    ]
