# Generated by Django 3.2.1 on 2024-03-21 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20240320_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='broadband',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.broadband'),
        ),
    ]
