# Generated by Django 3.2.1 on 2024-03-21 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_userprofile_broadband'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nccoutlet',
            name='broadband',
        ),
        migrations.RemoveField(
            model_name='reactivationreport',
            name='broadband',
        ),
        migrations.RemoveField(
            model_name='uploadphoto',
            name='broadband',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='broadband',
        ),
    ]
