# Generated by Django 3.2.1 on 2024-03-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20240321_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadphoto',
            name='Region',
            field=models.CharField(choices=[('North East', 'North East'), ('North West', 'North West'), ('South East', 'South East'), ('South South', 'South South'), ('Lagos', 'Lagos'), ('West', 'West')], default='North East', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadphoto',
            name='State',
            field=models.CharField(default='kano', max_length=100),
        ),
    ]
