# Generated by Django 3.2.1 on 2024-03-21 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20240321_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadphoto',
            name='Post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
