# Generated by Django 3.2.1 on 2024-03-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_uploadphoto_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadphoto',
            name='Post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
